spring:
  r2dbc:
    url: r2dbc:postgresql://192.168.3.15:25566/pay
    username: postgres
    password: mysecretpassword
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
  webflux:
    base-path: /v1
springdoc:
  version: 1.0
  api-docs:
    path: /api-docs
gis:
  url: https://gmf-gis.ddns.net/api
  token: oP%L&2i!5i6W43n86!hl3$kmroxraiOFsY3i#6JskAWuLKHH*LBYGjJDOiKRiI!v14LC94HACrFclU!e#RZAwD40UP&yw&O7fd9
server:
  address: 0.0.0.0